### PR TITLE
Fixs.

### PR DESCRIPTION
**Pull request by Argalep**
* RuneBook Gump EC fix.
* Pet All Guard command AI fix.

### CODE REVIEW

**Comment by kevin-10** [comment]
What exactly needed to be fixed on the runebook gump?  Also, what is the difference with the new HtmlIntern and HtmlLocalized method added to Gump.cs?

As for the pet stuff, I thought the issue was a guarded pet didn't attack another blue creature?

**Comment by Tasanar** [comment]
https://trueuo.com/index.php?threads/enhanced-client-rune-books.902/#post-4470

Dexter look there. The EC uses a completely different gump and color scheme for rune books.

**Comment by kevin-10** [comment]
Ok, so will this now display properly on EC as well as CC?

**Comment by Tasanar** [comment]
No idea I haven't tested it and won't have time for a few days. Just saw the traffic and wanted to show you the screen shots.

**Comment by kevin-10** [comment]
ill try tonight.  Im been busy as well!

**Comment by kevin-10** [comment]
Ok, looks good. For the DoOrderGuard(), can we loop the table so if for some reason, the closest target fails, it can move to the next closest target?

**Pull request merged**
