### PR TITLE
Fixes a cliloc error

### PR DESCRIPTION
**Pull request by Tasanar**
Fixes a cliloc error reported on the forums.

### CODE REVIEW

**Comment by Tasanar** [comment]
Removed un-needed code in PaladinSpell

The saying of the mantra is already defined in Spell.cs

PaladinSpell was the only magic school to have an override, that is not needed.

**Comment by kevin-10** [comment]
This spell mantra may have issues that come up later, or at least inconsistencies with EA unless verified. It looks like the override was to make the spell mantra the same color regardless of speech hue, and whatever MessageType does which can have effects on journal logging etc.

The difference, Spell.cs:

m_Caster.PublicOverheadMessage(MessageType.Spell, m_Caster.SpeechHue, true, m_Info.Mantra, false);

In PaladinSpell:

Caster.PublicOverheadMessage(MessageType.Regular, 0x3B2, MantraNumber, "", false);

**Comment by Tasanar** [comment]
So on real UO too, Chiv is the only one that acts differently?

**Comment by kevin-10** [comment]
Im not sure. We'd have to test.

**Pull request merged**
