### PR TITLE
Final fix.

### PR DESCRIPTION
**Pull request by TrueUO**
Final Fix

### CODE REVIEW

**Comment by kevin-10** [comment]
So its not doing an IsFriend check?

**Comment by TrueUO** [comment]
I really do not think it is needed when you look at the whole method from before;

The IsFriend was in the fraction brackets, so when we deleted the whole method it was only checking again, sanity?, that still !is not this or that, when now it does not need to. No idea if that makes sense but if you look at BaseAI from two days compared to this it seemed the right answer.

**Comment by TrueUO** [comment]
Argalep can you look at this too?

**Comment by kevin-10** [comment]
Gotcha. Im at work and don't like looking at old versions through github.

**Pull request merged**
