### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by kevin-10**
- Fixed Insciption Bug with arch cure scrolls
- Added new magincia regions for proper house placement
- Heightened Senses now applied the correct parry Bonus
- Dice can now have security level Set
- Blood Oath no longer factors resist spells in PVP, per EA
- Added 'stablecount' command to animal trainers
- Fixed 2x loot for fire steeds
- Revenants and Covetous Revenants should now be wearing hooded robes!
- Shrine of Singluarity quest (on fail) is now 2 real hours, 24 UO hours
- Fixed assessibility issue with mailboxes
- Goza mats and tessens now retain the color of the cloth uses to craft them with
- Removed [voidpool command as it is not needed
- Despise pets should now attack opposite aligned creatures, as well as the bosses properly
- Anticipate his should now function properly when using confidence
- Body guard should be block/transfer the proper amount of damage
- Fixed Body Guard buff icons

### CODE REVIEW

**Comment by Tasanar** [comment]
Looks good. Only thing I noticed was some debugging code left in Despise Creatures.
m_Creature.DebugSay("I have detected {0} as an aggressor, attacking", m_Creature.FocusMob.Name);

**Comment by kevin-10** [comment]
Damn, can't get anything past you!

**Comment by kevin-10** [comment]
No, thats fine, that is in all AI code. Only displays if debug = true.

**Comment by Tasanar** [comment]
Ah I see now, sorry looks great! Thanks for all you do.

**Comment by kevin-10** [comment]
Without you guys, id be bored!

**Pull request merged**
