### PR TITLE
Miscellaneous Gumshoe Quest Corrections

### PR DESCRIPTION
**Pull request by Hjornskar**
Corrections to better match the Gumshoe Quest. Gump images, decorations, functions of various items, missing items, including sound effects and overhead messages, matching decorative items and hues.

### CODE REVIEW

**Comment by Tasanar** [comment]
Could you try again? Travis CI found an error and now it is blocked.

**Comment by kevin-10** [comment]
YOu have missing files from the project.

**Comment by Hjornskar** [comment]
I don't understand what it's getting hung up on.

**Comment by Hjornskar** [comment]
Made some minor corrections and affixed a forgotten .cs to one file. Not sure what else is causing it to hang up.

**Comment by kevin-10** [comment]
You have to include the new files in the project:

https://github.com/ServUO/ServUO/blob/master/Scripts/Scripts.csproj

**Comment by Hjornskar** [comment]
Okay, got it. Thank you for your patience!

**Comment by Tasanar** [comment]
Looks good, going to let Dexter give it a once over since he coded the original.

Dexter will simply de-spawning and re-spawning the Seasonal Khaldun event fix this?

**Comment by Tasanar** [comment]
We have not forgotten about this. Dexter is just busy IRL right now but will return soon.

**Pull request merged**
