### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by kevin-10**
- Converted Searing Weapon to ItemSocket, mych like caddellite, honestyItem, etc
- SearingWeapon no works per EA
- PrimevalLich debuffs are now debuffs
- added message when gregorio cannot be damaged
- healing bonus adjusted for looting rights
- Imbuing min success chance is now 0%, no longer will go negative
- Removed CommandProperty attribute from property casuing client crashes in BaseBook

### CODE REVIEW

**Comment by Argalep** [comment]
World: Loading...
An error was encountered while loading a saved object
 - Type: Server.Items.Mace
 - Serial: 0x40198D88
Delete the object? (y/n)

**Comment by kevin-10** [comment]
Did you hit n to see what the error was?

**Comment by Argalep** [comment]
After pressing return an exception will be thrown and the server will terminate.

**Comment by Argalep** [comment]
Error:
System.Exception: Load failed (items=True, mobiles=False, guilds=False, data=False, type=Server.Items.Pike, serial=0x403A1B77) ---> System.NullReferenceException:  Object reference not set to an instance of an object.
   location: Server.Items.SearingWeapon..ctor(BaseWeapon wep) ..\Scripts\Items\Internal\ItemSockets\SearingWeapon.cs in: line 17
   location: Server.Items.BaseWeapon.Deserialize(GenericReader reader) ..\Scripts\Items\Equipment\Weapons\BaseWeapon.cs in: line 4540
   location: Server.Items.BaseMeleeWeapon.Deserialize(GenericReader reader) ..\Scripts\Items\Equipment\Weapons\BaseMeleeWeapon.cs in: line 62
   location: Server.Items.BaseSpear.Deserialize(GenericReader reader) ..\Scripts\Items\Equipment\Weapons\BaseSpear.cs in: line 61
   location: Server.Items.Pike.Deserialize(GenericReader reader) ..\Scripts\Items\Equipment\Weapons\Pike.cs in: line 122
   location: Server.World.Load() ..\Server\World.cs in: line 661
   --- İç özel durum yığını izlemesinin sonu ---
   location: Server.World.Load() ..\Server\World.cs in: line 884
   location: Server.Core.Main(String[] args) ..\Server\Main.cs in: line 645
This exception is fatal, press return to exit

**Pull request merged**
