### PR TITLE
fixs.

### PR DESCRIPTION
**Pull request by Argalep**
* Travesty Spawn Helper Fix.
* Gargoyle items are not loot

### CODE REVIEW

**Comment by Tasanar** [comment]
The specific way Hephaestus is created right now, Antique vs not, will also make altering it challenging. Just one example.

**Comment by Argalep** [comment]
Hephaestus may not be an antique item.

screenhunter 173
screenhunter 174
screenhunter 175

**Comment by Tasanar** [comment]
If it comes from the Void pool it is antique.

If it comes from Cora it is not.

Also there are a bunch of TOL items currently that do not alter correctly if we approve this.

**Comment by Tasanar** [comment]
So lastly what about the Hephaestus shield?

If you alter an Antique one will it still have Antique and vice versa?

**Comment by Argalep** [comment]
Items received as a reward cannot be alterabled. That is, you cannot alter the antique.

**Comment by Tasanar** [comment]
But how does it know? They are both derived from the same item

**Pull request merged**
