### PR TITLE
* New Magincia Marketplace Text  fix.

### PR DESCRIPTION
**Pull request by Argalep**

### CODE REVIEW

**Comment by kevin-10** [comment]
Does this work ok on Classic Client as well?

**Comment by Argalep** [comment]
Yes

**Comment by Tasanar** [comment]
actually Argalep can you double check https://github.com/ServUO/ServUO/pull/4037/files#diff-3698145f26cc1a4c9590bd766592b735

**Comment by kevin-10** [comment]
Maybe remove the {0} argument?

**Comment by Argalep** [comment]
@Tasanar Would you check again?

**Pull request merged**
