### PR TITLE
Bug Fix.

### PR DESCRIPTION
**Pull request by Argalep**
* Add 2018 Holiday Gift Token
* add holiday wreath
* add holiday sign
* fix Paroxymus Peerless (The entrance to the boss requires the use of an iron gate.)
* fix. Prism Of Light Altar

### CODE REVIEW

**Comment by kevin-10** [comment]
Well done! Did you add a way for that iron gate to be added on existing shards?

**Comment by Argalep** [comment]
> Well done! Did you add a way for that iron gate to be added on existing shards?

No

**Comment by kevin-10** [comment]
You can probably version the paroxysmus altar (in deserialize) and place it that way.

**Comment by kevin-10** [comment]
Also, Dan noticed KeyCount was 16?

**Comment by Argalep** [comment]
> You can probably version the paroxysmus altar (in deserialize) and place it that way.

I'm looking at the baby at home :) it may take me a while to do it. Can you do it?

**Pull request merged**
