### PR TITLE
Update Honor.cs

### PR DESCRIPTION
**Pull request by Tasanar**
Missing various system messages for the Honor virtue.
https://www.servuo.com/threads/honor-virtue-missing-a-few-messages.8962/

### CODE REVIEW

**Comment by kevin-10** [comment]
Whats up withthe Travis CI errors?

**Comment by Tasanar** [comment]
I have NO idea what any of that means.

All I did was add in a few lines, that I already applied to Heritage, for the missing system messages.

**Comment by Tasanar** [comment]
When you get home take a look from your computer. I already applied it to Heritage and it works great. When I looked at the errors it also had nothing to do with Honor, the only script I edited. Maybe because I make my commits by editing the script through GitHub? Not actually uploading anything? No idea what TravisCI is or what it does.

**Comment by Xeroxxx** [comment]
The travisci errors happening for month. The are showing up because I submitted the fix and its working again. So it switches from permanent error to failed. No worries it still compiles, just a case sensitive issue.

**Comment by Xeroxxx** [comment]
Sp it gets deactivated if there are too many fails, no it works basiclly again and starts being displayed.

**Comment by Xeroxxx** [comment]
@kevin-10 I will message you on discord tomorrow.

**Pull request merged**
