### PR TITLE
Add item decay config

### PR DESCRIPTION
**Pull request by dariys**
Add item decay tooltip
Add config for item decay timer
Add virtual property to allow derived items to specify a multiple of the default decay time

### CODE REVIEW

**Comment by Xeroxxx** [comment]
I would like to see the options in General.cfg, not worth it adding separate configfile for two options. We already have a shit ton of configs :D

**Comment by kevin-10** [comment]
Are there any items that show the decay time for actual decay?  If not, I don't see a need to make core edits for custom code.

**Comment by dariys** [comment]
@Xeroxxx - I'll move the config options into General.cfg

@kevin-10 - I'm adding an option here to display decay via tooltip to users.  If this is enabled (off by default, to match standard behavior) - when hovering over items, it shows in the tooltip for items (i.e. stuff on the ground)

**Comment by dariys** [comment]
@Xeroxxx - Looking at the options in General.cfg though - these really don't seem like they fit there...

**Comment by kevin-10** [comment]
I get that, but like I said, I don't see a need to make core edits for custom code. Look at BaseDecayingItem.cs if you want to use this functionality.

**Comment by dariys** [comment]
@kevin-10 Just to be clear - this is for all items that decay from the world - i.e. dropped on the ground - piles of ore, logs, whatever.  This change makes the decay time configurable (from the default of one hour), and adds the configuration to display that time on the tooltip of the item (again - only when the item is on the ground.  When it is in the bag, there is no decay display on the tooltip).  The only piece of code that supports custom edits is the decay multiplier - which for example - I have ore set to a higher multiplier so it lasts longer.  If that is the piece you object to - I can remove that.

**Comment by Xeroxxx** [comment]
Well, I mainly follow @kevin-10 opinion. IMHO making DecayTimer configurable is useful, without adding the tooltip. However everything fits in General.cfg, doesn't matter whats in there, because its "General".

**Comment by kevin-10** [comment]
@dariys I'm ok with the decay modifier, just don't think we need the addition to the object property list.

**Comment by dariys** [comment]
@kevin-10 Even as a configurable option?  It's defaulting to false (not shown) with what I've submitted here.

**Comment by Xeroxxx** [comment]
@Tasanar 
Configurable DecayTimer and Multiplier is still a core modification with or w/o tooltip.

I agree with @kevin-10 configurable DecayTimer and Multiplier is ok. I pledge for moving it in general.cfg no need for new configs. Tooltip is not necessary.

**Comment by Tasanar** [comment]
I know, I just meant the tooltip edits.

**Comment by kevin-10** [comment]
Agreed. @dariys, just remove the tooltip (object property stuff) but the config stuff is ok for decay boolean and decay multiplier.

**Comment by dariys** [comment]
Updated

- config is now in general.cfg
- Only decay time & decay override mechanics included - tooltip addition is removed

**Pull request merged**
