### PR TITLE
* New Magincia Marketplace Text fix.

### PR DESCRIPTION
**Pull request by Argalep**

### CODE REVIEW

**Comment by kevin-10** [comment]
Is this tested with all the different possible messages? I have a workaround that works. Also, how did you know to put "empty"?  Packet sniffers?

**Comment by Argalep** [comment]
The client is having problems when the parameter is null. I saw that it works correctly in any word. If you have a better solution, we can try it.

**Comment by kevin-10** [comment]
For the one with an empty string, I used the \t and it worked.

**Comment by kevin-10** [comment]
How did you know to use the @ symbol?

**Comment by Argalep** [comment]
I have encountered the problem found in the Ultima Store menu.  OSI is also used this way


https://github.com/ServUO/ServUO/blob/master/Scripts/Services/UltimaStore/UltimaStoreGump.cs

**Pull request merged**
