### PR TITLE
Revert "Replacing OppositionGroup with OppositionList v1.1"

### PR DESCRIPTION
**Pull request by kevin-10**
Reverts ServUO/ServUO#1908

Reverting as it was incomplete, and more importantly, the old system worked just fine.

### CODE REVIEW

**Comment by GriffonSpade** [comment]
What do you mean it was incomplete? It had everything that OppositionGroup had.

**Comment by techy2493** [comment]
@Vorspire @dmurphy22 @kevin-10 

Can anyone explain how the code got in the repo in the first place if it was just going to be reverted in a few days? 

@kevin-10 You were vocal in the original PR, why did you not raise these concerns before?

**Comment by kevin-10** [comment]
I was under the assumption that the original system didn't work by testing the wrong creatures.  Once I realized that, I went back to the old system and found it worked just fine.  With that being said, I apologize for any time wasted on this but the way I see it, it works just fine.  Let's not reinvent the wheel.  The  Not thing this system needs is the addition of gray vs green goblins.

**Comment by GriffonSpade** [comment]
Um, I'm a bit confused how you came to that impression. This was the very first paragraph in the notes: "Alright guys, this is ready, and should work better. However, it's replacing stable, if clunky, code, so please test and review for a while to make sure nothing unexpected becomes a problem."

Further, there's a reason why we do not use wooden wagon wheels on cars. There's no point in reinventing the wheel, but there _**IS**_ a point in inventing a _**BETTER**_ wheel

**Comment by kevin-10** [comment]
Cool, I get it.  If @Vorspire or @dmurphy22 decides to re-commit, I'm fine with it.  I believe the old system is much less clunky, and works exactly how its supposed to.  As for the merge and revert, I apologize.

**Pull request merged**
