### PR TITLE
Enhanced client - some fixes

### PR DESCRIPTION
**Pull request by maicomstoppa**
fixes:
-hotbar (skills, items, spells)
-missing strings
-enhanced client support flag
-enhanced client detect

### CODE REVIEW

**Comment by kevin-10** [comment]
Please remove the server configs you have on your setup.

**Comment by maicomstoppa** [comment]
kevin-10, I would love to, but I coudn't manage to do so.
Can you direct me towards on how I exclude a commit from a branch?
I tried everything in this Desktop GitHub.

**Comment by maicomstoppa** [comment]
I'll try to start the process from the beggining ASAP, and find out what I'm doing wrong.

**Comment by kevin-10** [comment]
I can manually merge it if you'd like.  Let me know.

**Pull request closed without merging**
