### PR TITLE
Removed IUsesRemaining from axes. 

### PR DESCRIPTION
**Pull request by kevin-10**
Confirmed on EA that axes DO NOT BREAK from lumberjacking

### CODE REVIEW

**Comment by jdphenix** [comment]
Do not axes break from use on siege perilous?

**Comment by kevin-10** [comment]
Yes, according to UOGuide, but not on regular production shards.  I used 500+ swipes and no breakage.

**Comment by GriffonSpade** [comment]
...Do we have a configuration setting for Siege Perilous style? If not, perhaps a Milestone Task?

**Comment by kevin-10** [comment]
That would be a monumental task but I'd be down.

**Pull request merged**
