### PR TITLE
Bug Fix for The Sewing Kit can make strange items.

### PR DESCRIPTION
**Pull request by uomamoru**
The Sewing Kit can make strange items named "Combine Cloth" and "Cut-Up Cloth" if you push the button on "CraftGumpItem" (not on "CraftGump") to make it.
By the way there is similar code in "CraftGump.cs" line 475.

### CODE REVIEW

**Comment by Tasanar** [comment]
How can I replicate this in-game?

**Comment by uomamoru** [comment]
1. Buy a Sewing Kit and a Bolt of Cloth from NPC vendor. 
2. Double click a Sewing Kit.
3. Push "Detail" button at "Cut-Up Cloth".
4. Push "Make" button.

**Comment by Tasanar** [comment]
@kevin-10 the bug is thereI confirmed it. I will let you review this.

**Comment by uomamoru** [comment]
Oh, I found new same problem by pushing "Make Number" and "Make Max".

**Comment by kevin-10** [comment]
Ah! Yes thanks. We need to get into EA and see what happens when you use Make Number/Max with these specialty crafts.

**Pull request merged**
