### PR TITLE
Starting to fix Oil Flasks

### PR DESCRIPTION
**Pull request by Tasanar**
Please review. 

https://www.servuo.com/threads/mechanical-pet-leather-wolves.9066/

FlaskOfOil was not used. I deleted it since the item is called an OilFlask

I also believe it makes more sense to be in Resources.

### CODE REVIEW

**Comment by kevin-10** [comment]
Was it not used at all?  If it was, you can use TypeAlias in the new oil flask so any existing won't be deleted:

[TypeAlias("Server.Items.FlaskOfOil ")]
public class OilFlask: Item
{

**Comment by Tasanar** [comment]
No it was not. If you look it was only referenced once in ModifiedClockworkAssembly but was commented out. It never naturally spawned anywhere or did anything.

**Comment by kevin-10** [comment]
Yea but other shards may have spawned them.

**Comment by Tasanar** [comment]
Done sir.

**Pull request merged**
