### PR TITLE
+ Ranged item and mobile update fixes.

### PR DESCRIPTION
**Pull request by Vorspire**
Attempt to fix the oddities caused by range-based entity updates while moving or teleporting around the world.

This also fixes inconsistencies with the Green and Yellow health bars for both classic and enhanced clients.

### CODE REVIEW

**Comment by Tasanar** [comment]
Do not merge this. There are some issues with mobiles loading which I communicated with Vorspire.

Mobiles will not load. They will show on their teleporters but you can not actually see them.


last10

**Comment by Tasanar** [comment]
Vorspire asked me to just test the Main.cs and ignore these other changes so I am going to do that quickly and will report back here.

**Comment by Tasanar** [comment]
I added the newest updates and everything works great!

I can still get teleporters to bug out and every now and then a mobile but after getting things to bug out over 20 times not a single item bugged out. There still seems to be some minor underlying issues but this is a huge improvement and a step in the right direction. Will take a few days with multiple people on to know the true extent.

**Comment by Tasanar** [comment]
After a few hours on the live shard there have been many reports of mobiles and houses not loading, even on the same screen.

**Comment by kevin-10** [comment]
2 things they need to relay.  1, are they teleporting in, or walking around? 2, what is their screen size.

**Comment by Tasanar** [comment]
Sometimes they are teleporting in other times just walk around Luna a house will not load. Screen sizes are random, the only thing in common is all use the newest client.

**Comment by kevin-10** [comment]
Do you have these changes on your shard? I'm running around Luna in all screen sized and can't get this to happen.

**Comment by Tasanar** [comment]
Yes and I got a few players screen shots tonight, which I sent to Vorpire. I could also do it right in front of him and he is able to replicate it.

**Comment by Tasanar** [comment]
I am also just running 800x600

**Comment by kevin-10** [comment]
What exactly are you doing to get it to malfunction?

**Comment by Tasanar** [comment]
Make a quick shard and message me on Discord with the info and I'll show you.

**Comment by Tasanar** [comment]
Get on Discord and join me and Vorspire.

**Comment by kevin-10** [comment]
HouseFoundation.cs will need to have its override removed as well.

**Pull request merged**
