### PR TITLE
Add basic configuration

### PR DESCRIPTION
**Pull request by castanhojfc**
This PR will add the basic configuration for the shard, that is, it sets its name and configs the caps. As a bonus the Ultima Store is disabled. Some notes about it are also provided in the readme.

### CODE REVIEW

**Comment by castanhojfc** [comment]
I've created this PR by accident

**Comment by TrueUO** [comment]
All good! :)

**Comment by deccer** [comment]
Ha it took me some time to realize i started a review on a closed PR ;)

**Comment by castanhojfc** [comment]
Hehe, I am crafting my own personal shard to have some fun at home, I really like this game and I want to enjoy the latest content.

**Comment by TrueUO** [comment]
Rock on brother! :)

**Pull request closed without merging**
