### PR TITLE
*Alter Item Fix

### PR DESCRIPTION
**Pull request by Argalep**
* add AlterContract

Change to Royal City regions

`<region type="TownRegion" priority="50" name="Royal City">
      <rect x="635" y="3303" width="300" height="400" />
      <rect x="961" y="3297" width="44" height="339" />
      <go x="750" y="3450" z="-20" />
      <music name="RoyalCity" />
      <entrance x="841" y="3510" />
      <region name="Royal Soulforge">
        <rect x="745" y="3371" width="8" height="8" />
        <go x="797" y="3436" z="-10" />
				<music name="QueenPalace" />
      </region>
      <region name="Queen's Palace">
				<rect x="717" y="3339" width="68" height="73" />
				<go x="748" y="3357" z="55" />
				<music name="QueenPalace" />
			</region>
    </region>`

### CODE REVIEW

**Comment by kevin-10** [comment]
Good stuff!

**Comment by Ravenwolfe** [comment]
I'm confused by this one. I cant find any record in OSI of an Alter Contract. Can you please provide more information?

**Comment by Argalep** [comment]
http://uo2.stratics.com/miscellaneous/altering-items/

**Comment by Ravenwolfe** [comment]
Manually added due to conflict. Thanks!

**Pull request closed without merging**
