### PR TITLE
Add SetMutateAction helper function to the craft system.

### PR DESCRIPTION
**Pull request by DarkLotus**
Enables people to set a callback action to mutate an individual craft entry without needing to modify the base Type.

Example usage
``` 
index = AddCraft(typeof(EnchantedApple), 1073108, 1072952, 60.0, 85.0, typeof(Apple), "Red Enchanted Apple", 1, 1044253);
SetMutateAction(index,(player, item, tool) => { item.Hue = 55; });

index = AddCraft(typeof(EnchantedApple), 1073108, 1072952, 60.0, 85.0, typeof(Apple), "Green Enchanted Apple", 1, 1044253);
SetMutateAction(index,(player, item, tool) => { item.Hue = 99; });
```

Etc, access to the crafted item, the crafter and the tool used is provided in the callback.

### CODE REVIEW

**Comment by kevin-10** [comment]
I think we already have something like this.

**Comment by kevin-10** [comment]
See:
        /// <summary>
        /// this delegate will handle all crafting functions, 
        /// such as resource check, actual crafting, etc. 
        /// For use for abnormal crafting, ie combine cloth, etc.
        /// </summary>
        public Action<Mobile, CraftItem, ITool> TryCraft { get; set; }

        /// <summary>
        /// this func will create complex items that may require args, or other
        /// things to create that Activator may not be able to accomidate.
        /// </summary>
        public Func<Mobile, CraftItem, ITool, Item> CreateItem { get; set; }

        public Func<Mobile, ConsumeType, int> ConsumeResCallback { get; set; }

**Comment by DarkLotus** [comment]
The above "CreateItem" is for when you want to entirely override the created item though, this helper just mutates the created item.

**Comment by kevin-10** [comment]
Ahh, yes you are correct. I will re-open and approve.

**Pull request merged**
