### PR TITLE
Add Triton and Fixs.

### PR DESCRIPTION
**Pull request by Argalep**
* add Triton
* auction safe fix
* NewMaginciaMessageGump fix.
* Vendor Search Map fix

### CODE REVIEW

**Comment by kevin-10** [comment]
Approved but I don't like changing BaseGump back go Gump, as BaseGump was supposed to be an improvement over Gump. Not a big deal though.

**Comment by kevin-10** [comment]
Also for the Triton, we should just change IMountStatuette to ICreatureStatuette. I don't see a reason it needs to differentiate between BaseMount and BaseCreature.

**Comment by Tasanar** [comment]
So why was BaseGump changed back to Gump?

**Comment by kevin-10** [comment]
It's not a big deal, but base gump has alot of convenience features and Refresh() which makes is so you can resend the same gump without having to construct a new one.

**Comment by Tasanar** [comment]
I will let @Argalep decide if he wants to push as is, or change it.

**Comment by kevin-10** [comment]
ok cool.  And @Argalep not a big deal, if none of the BaseGump functionality isn't used, we're good.

**Pull request merged**
