### PR TITLE
fix.

### PR DESCRIPTION
**Pull request by Argalep**

### CODE REVIEW

**Comment by Tasanar** [comment]
https://uo.com/wiki/ultima-online-wiki/items/veteran-rewards/

I would 1. Add a check for IsRewardItem and also veteran rewards, including these, can be used by anyone.

**Comment by Tasanar** [comment]
"All rewards can only be claimed by accounts of the required age, but most can be traded to, and used by younger accounts. This does not apply to ‘account bound’ rewards such as the red soulstone and shard shields."

Taken from official UO wiki.

**Comment by Argalep** [comment]
http://www.xn--28j2a0gvbiy.com/entry/2012/11/26/121008

image

The picture also says in the message of use:

"Your account is not old enough to use this item. Months until you can use this item : 8"

**Comment by Tasanar** [comment]
That is older. They removed all age restrictions except for soul stones and shard shields.

**Comment by Tasanar** [comment]
http://www.uoguide.com/Publish_83
https://www.servuo.com/threads/veteran-rewards-no-longer-require-a-set-age-to-use-just-to-claim.4060/

"*Removed account age limit to use vet reward items. This change does not remove the account bound limitation set on some vet rewards."

**Comment by Tasanar** [comment]
Those pictures are from when the rugs first came out. They have completely changed since then.

**Comment by kevin-10** [comment]
Who should be able to take the item then?  I would say anyone on the owner account and/or anyone on the account that placed the addon.

**Comment by Tasanar** [comment]
I would say house owner. There is a chance these have an access level any anyone with that access level can take.

**Comment by Argalep** [comment]
When you convert the addon to deed, will not write veteran reward on deed

**Pull request merged**
