### PR TITLE
Stable slots

### PR DESCRIPTION
**Pull request by NickEU**
Two bonus stable slots from SA

### CODE REVIEW

**Comment by qbradq** [comment]
Please use the expansion checks. If(Core.SA) {max+=2;}

**Comment by NickEU** [comment]
Thanks. Will this work?

**Comment by qbradq** [comment]
Thanks perfect! I didn't know there were bonus stable slots for TOL. I'll go ahead and merge this, but can you provide some reference for those TOL stable slots?

**Comment by NickEU** [comment]
[UoGuide](http://www.uoguide.com/Time_of_Legends)

> Stable Slots - 2 additional stable slots for all upgraded accounts.

**Comment by qbradq** [comment]
Thanks so much!

**Comment by NickEU** [comment]
[This](https://github.com/ServUO/ServUO/issues/292) issue can now be closed, i think i screwed up and didn't link the PR and issue somehow? Is there a way to do that?

**Pull request merged**
