### PR TITLE
*add Termur PvPWarn Gump (reference:xrunuo)

### PR DESCRIPTION
**Pull request by Argalep**
change to PvPWarnTeleporter
511,584,11,TerMur,6992,1367,-15,Felucca,False
512,584,11,TerMur,6992,1367,-15,Felucca,False
513,584,11,TerMur,6993,1367,-15,Felucca,False
514,584,11,TerMur,6993,1367,-15,Felucca,False

7149,756,25,Felucca,974,419,-21,TerMur,True
7150,756,26,Felucca,975,419,-21,TerMur,True
7151,756,25,Felucca,976,419,-21,TerMur,True
7152,756,25,Felucca,977,419,-21,TerMur,True

### CODE REVIEW

**Comment by kevin-10** [comment]
Why are you removing all of the High Seas stuff from csproj?

**Comment by Argalep** [comment]
The files under this folder have been moved to another location. Give project warning

**Comment by kevin-10** [comment]
OH I see, but the new location for the files are in there?

**Comment by Argalep** [comment]
Scripts/Services/Expansions/High Seas

**Pull request merged**
