### PR TITLE
Trashing blessed Items #1859 fix.

### PR DESCRIPTION
**Pull request by ruaduck**
You can delete blessed items per EA.  Tested with Spell Books, Fountain of Life Deed, and Robes that are blessed. Tested by ruaduck.

### CODE REVIEW

**Comment by Tasanar** [comment]
You can ONLY trash blessed items that are worth clean up points. Try to trash any veteran reward, or bless a crimson cincture and try to trash it and it will not let you.

**Comment by Tasanar** [comment]
This commit reverts a change Dexter added in months ago to address this. It's not perfect but I would rather have it the old way until all clean up items are added for points.

**Comment by Tasanar** [comment]
I think more testing needs to be done. It will not let me trash a lot of blessed items in Test Center.

**Comment by ruaduck** [comment]
Closed this pull request in light of Tasanar's and Kevin-10's comments.

**Pull request closed without merging**
