### PR TITLE
Add Server.Tests project

### PR DESCRIPTION
**Pull request by mchekin**
Creating a Server.Tests project for testing Server project using xUnit.

- Basic tests for AggressorInfo.cs

### CODE REVIEW

**Comment by mchekin** [comment]
@Vorspire 
@TrueUO 

Please tell me if this pull request makes sense to you or not.

**Comment by mchekin** [comment]
@Vorspire 
@TrueUO 

Good day.

I know you are probably very busy, but I would really appreciate if you can take a look at this pull request, when you have time.

**Comment by TrueUO** [comment]
> @Vorspire
> @TrueUO
> 
> Good day.
> 
> I know you are probably very busy, but I would really appreciate if you can take a look at this pull request, when you have time.

Hey friend, do you have Discord by chance?

**Comment by mchekin** [comment]
@TrueUO 
Hello :)
Yes I am in the ServUO Discord.

**Pull request closed without merging**
