### PR TITLE
Myrmidex Invasion fix

### PR DESCRIPTION
**Pull request by Argalep**
* BritannianInfantry fix
* Tribe spawns only BritannianInfantry
* flag fix location
*  creature vs creature corpse delete

### CODE REVIEW

**Comment by kevin-10** [comment]
So the corpses only disappear if they are killed by another creature?   What if a players pet kills it?

**Comment by Argalep** [comment]
Corpse will not disappear when player or his pet kills. I would appreciaye if you can handle the other issue

**Comment by kevin-10** [comment]
Disregard, notoriety has to be handled the way you did, Region only handles harmful/beneficial actions.

**Comment by kevin-10** [comment]
Looks good, but one issue with IsEnemy.  The allegience check needs to be first so they attack players not aligned.  You have it returning false if its a player before the allegience check.

**Pull request merged**
