### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Vorspire**

### CODE REVIEW

**Comment by TrueUO** [comment]
Would that make the gift giving packages hand out yearly?

**Comment by Vorspire** [comment]
Yes, which seems to be what every single shard edits the files to do anyway.

**Comment by TrueUO** [comment]
Yeah, I would advise them against that.

If anything we should combine them all into one folder with one GiftGiver.cs as an example and shard owners can then deploy all those different gift packages at will. I will do that over at TrueUO and push it here for review.

**Review by TrueUO — CHANGES_REQUESTED** [review]
GiftGiving. Leave dates as is for now to let shard owners decide how to deploy. 

Will work on condensing them all into one folder with one GiftGiver.cs

**Review by TrueUO — APPROVED** [review]

**Review by TrueUO — APPROVED** [review]

**Pull request merged**
