### PR TITLE
Added Queens Loyalty and SA RegionDrops.

### PR DESCRIPTION
**Pull request by Ravenwolfe**
Used a separate branch so that you can test fully.

### CODE REVIEW

**Comment by qbradq** [comment]
This may conflict with the changes I made to Raptor.cs and StoneSlith.cs. Just remove my version of OnDeath() and take Ravenwolfe's.

**Comment by Ravenwolfe** [comment]
I used the latest pull so I think I already removed those conflicts before
I sent the request, but probably good to double check.

**Comment by qbradq** [comment]
Noting that Ter Mur housing does not work due to not having regions set up for it. We can make the change on our side though.

**Comment by Ravenwolfe** [comment]
Ah, sorry about that, you want me to send you the regions file we have?

**Comment by Ravenwolfe** [comment]
Had to zip it since github doesn't allow xml. Probably wanna merge or use this one since it has the correct regions for the SA region drops as well. They are OSI accurate.
[Regions.zip](https://github.com/ServUO/ServUO/files/88916/Regions.zip)

**Comment by qbradq** [comment]
Thanks! I am also going to note here the tweaks I am doing on our side for OSI accuracy in case you want to do that on your side. I am basing this on the information on this stratics page: http://uo2.stratics.com/miscellaneous/gargoyle-queen-loyalty/ . If you have differing information please let me know!
* High Plains Boura QLPoints should be 15, not 10
* Toxic Slith QLPoints should be 30, not 20
* Anlorezen QLPoints should be 10 points, not 15
* Fire Ant QLPoints should be 2, not 20
* Vitavi [Renowned] should give 50 QLPoints
* Wyvern [Renowned] should give 50 QLPoints
* Axem’s “A Broken Vase” quest QLPoints should be 5, not 50
* Axem’s “Putting The Pieces Together” quest QLPoints should be 15, not 150
* Axem’s “Ye Olde Gargish” quest QLPoints should be 50, not 500
* Sliem the Fence’s “Unusual Goods” quest should give 75 QLPoints
* Aliabeth the Tinker’s “The Exchange” quest should give 50 QLPoints
* Aliabeth The Tinker’s A Worthy Proposition Quest should give 35 QLPoints
* Ortanord should give 3 QLPoints
* Clan Ribbon Courtier shoudl give 5 QLPoints (this mobile may not be implemented yet)
* Gremlin should give 5 QLPoints
* Wolf Spider should give 5 QLPoints
* Green Goblin should give 8 QLPoints
* Green Goblin Alchemist should give 10 QLPoints
* Green Goblin Scout should give 10 QLPoints
* Rotworm should give 10 QLPoints
* Bloodworm should give 15 QLPoints
* Putrid Undead Gargoyle should give 15 QLPoints
* Lava Elemental should give 20 QLPoints
* Iron Beetle should give 20 QLPoints
* Navrey Night-Eyes should give 75 QLPoints
* Niporailem the Thief should give 75 QLPoints

**Comment by Ravenwolfe** [comment]
Awesome, thanks!

**Comment by qbradq** [comment]
This pull request is functionally sound. It just omits some of the point values or have them inaccurate. I'm going to merge as-is and open an issue to resolve the rest.

**Pull request merged**
