### PR TITLE
ParoxTeleporterFix

### PR DESCRIPTION
**Pull request by TrueUO**
https://github.com/ServUO/ServUO/pull/5072

Based on PR 5072 for publish 57.

### CODE REVIEW

**Comment by TrueUO** [comment]
https://github.com/ServUO/ServUO/pull/5072

**Comment by lilezek** [comment]
With this change the player won't get the message if they don't have a backpack. Is this intended? I'm not sure how can, a player,  lose their backpack at all.

**Comment by TrueUO** [comment]
No, its just closer to the actual check for the backpack or not. Inside the bracket. 

Everything still falls through. Test it out.

**Comment by TrueUO** [comment]
And you are exactly right. A players backpack should probably never be null, so nesting that message outside of the backpack check just didn't make sense. However, since it still falls through, unless it finds rope, you do still see the message. Just semantics. This also makes the changes to both the trammel and felucca teleporter.

**Pull request merged**
