### PR TITLE
* Creatures fix.

### PR DESCRIPTION
**Pull request by Argalep**
* add NightTerror.cs 
* Enraged Earth Elemental, Fire Daemon, Greater Poison Elemental, Lava Elemental fix

Missing Quest

https://uo.com/wiki/ultima-online-wiki/gameplay/quests/linzrom-the-guard-captain/

### CODE REVIEW

**Comment by kevin-10** [comment]
Please stop putting .this in front of everything!

**Comment by Tasanar** [comment]
Did the quest never get added?

**Comment by kevin-10** [comment]
What quest?

**Comment by Tasanar** [comment]
In his notes above on what was changed he had this

> Argalep commented 2 days ago • edited 
add NightTerror.cs
Enraged Earth Elemental, Fire Daemon, Greater Poison Elemental, Lava Elemental fix
Missing Quest

> https://uo.com/wiki/ultima-online-wiki/gameplay/quests/linzrom-the-guard-captain/

**Pull request merged**
