### PR TITLE
PublicMoongate.cs: Staff Overrides

### PR DESCRIPTION
**Pull request by GriffonSpade**
-Allows staff to use moongate regardless of status or range.
-Removed all occurances of 'this.' in the code.
-Replaced space indents with tab indents
-Added braces to all checks

Part of #778 Staff related "bugs" [https://www.servuo.com/threads/staff-related-bugs.4637/](url)

### CODE REVIEW

**Comment by kevin-10** [comment]
Whats the point of that editor file?  I thought it auto-formatted?

**Comment by GriffonSpade** [comment]
Might be related to the autoformatting -- I use Notepad++ to edit. 
I suppose I can convert them easily enough, though working with space indents is a bit of a pain, and I notice they tend to deform into irregular 3 and 5 space indents in places and need to be cleaned.

Give the word, boss, and I'll make it so.

**Comment by GriffonSpade** [comment]
Alrighty, I got that plugin, that should help. But ah, where do I edit the editorconfig file for it? I don't see anything about that at all.
(And I was calling @kevin-10 boss ;))

**Comment by ppardalj** [comment]
@GriffonSpade don't play with my heart like that :(

Hahah now seriously, I'm happy your PR is finally merged, congratulations!! :)

**Pull request merged**
