### PR TITLE
Missing Cloaks of Life, Death, and Power

### PR DESCRIPTION
**Pull request by Tasanar**
http://www.uoguide.com/Cloak_Of_Power
http://www.uoguide.com/Cloak_Of_Death
http://www.uoguide.com/Cloak_Of_Life
http://www.uoguide.com/Cloak_Of_Silence

Adding missing cloaks from EA event. All hues verified on EA. Correct clilocs.

This item derives from BaseOuterTorso because although it is an Elven Cloak, humans can wear it too.

### CODE REVIEW

**Comment by kevin-10** [comment]
Before you merge, make sure you add it to the csproj file.

**Comment by Tasanar** [comment]
How do I do that correctly? I have looked at it before but I never know where to put the correct edits.

**Comment by Xeroxxx** [comment]
If you're using Visual Studio, basiclly drag and drop it to the correct path in the solution explorer.

If using a text editior open Scripts.csproj and add the line:
`<Compile Include="Path\Path\File.cs" />` to an appropriate place. Preferably sorted by alphabet

**Comment by Tasanar** [comment]
Just looking at it I am not sure where to put it. It does not seem to be sorted.

**Comment by Xeroxxx** [comment]
Put it where you want it and it makes sense. Actually doesnt matter.

**Comment by Xeroxxx** [comment]
Maybe just before:
`    <Compile Include="Items\Artifacts\Equipment\Clothing\TheScholarsHalo.cs" />
    <Compile Include="Items\Artifacts\Equipment\Clothing\JadeArmband.cs" />
    <Compile Include="Items\Artifacts\Equipment\Clothing\MagicalDoor.cs" />`

**Pull request merged**
