### PR TITLE
 * EC Ultima Store fix part 1

### PR DESCRIPTION
**Pull request by Argalep**

### CODE REVIEW

**Comment by kevin-10** [comment]
Interesting. This must be EA's way of showing images/text on top of buttons?

**Comment by kevin-10** [comment]
Did you test this?  It's not working.

**Comment by Argalep** [comment]
image


I fixed my own repo. it works fine. you can test!

https://github.com/Argalep/ServUO

**Comment by kevin-10** [comment]
Ok, reopen it, my bad.

**Pull request merged**
