### PR TITLE
NewMobileAnimation Packet fix.

### PR DESCRIPTION
**Pull request by Argalep**
* add AnimationType
* Eat animation fix.
* Gargoyle fly animation fix.
* BaseCreature hurt animation fix.
* salute and bow animation fix.

### CODE REVIEW

**Comment by kevin-10** [comment]
Very nice work.  I was testing these last night.  Some are for gargs only (you've identified these) and some are for animal/monster types.  The animations such as block, parry, etc, are these used on EA?  Also, we'll need to implement the attack ones.   Each different attack type has its own action number.

**Comment by Argalep** [comment]
yes, block, parry etc. animations are used.

**Comment by kevin-10** [comment]
Ok, will you be working on that? If not, I can do it.

**Comment by Argalep** [comment]
Of course, you can work on it. I will inform you if I have a different information.

**Pull request merged**
