### PR TITLE
Custom Housing Optimization

### PR DESCRIPTION
**Pull request by Vorspire**
+ Prototyping optimizations for house customization.

### CODE REVIEW

**Comment by kevin-10** [comment]
I debated hiding other houses, it looked too custom to me.  Either way I'm good.

**Comment by Tasanar** [comment]
So no houses will show? That will definitely stick out to EA players. Dexters edits did fix the problem but if this is needed, so be it.

**Comment by Vorspire** [comment]
I don't see a reason why someone customising a house needs to be aware of other houses, and from what I've read on the matter so far, OSI haven't been consistent in fixing the issue. 

There is the added benefit of being able to build without an obstructed view if a large house is placed in front of yours.

**Comment by Tasanar** [comment]
Great point.

Merging now.

**Pull request merged**
