### PR TITLE
Add a recursive copy function to the autobackup

### PR DESCRIPTION
**Pull request by Elyrith**
Add a recursive copy function to the autobackup, rather than moving the folder.

I tested this on my Linux (Ubuntu 18.04) server and my Windows 10 server and the backups worked without losing my save data. (I was having no issues on Windows, but I tested it there to make sure I didn't break it.)

### CODE REVIEW

**Comment by Elyrith** [comment]
This *should* fix issue #3642

**Comment by Elyrith** [comment]
For the record, I 'borrowed' the code from here.
https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-copy-directories

**Comment by Vorspire** [comment]
I've made the necessary edits, please test on MONO again.

**Comment by Elyrith** [comment]
It was still using the non-Mono version before I added the flag for the make script.

I got the info from:
https://stackoverflow.com/questions/4406211/compiler-if-directive-to-split-between-mono-and-net

**Comment by Elyrith** [comment]
Wait, still testing...

**Comment by Elyrith** [comment]
This works for me in Linux with Mono.

I got my info from:
https://stackoverflow.com/questions/4406211/compiler-if-directive-to-split-between-mono-and-net

**Comment by Vorspire** [comment]
Everything in the ServUO project references the MONO directive, it would be best to stick with the status quo and use that instead of __MonoCS__ 

The make file included with ServUO should already define #MONO, as does the compile batch file for compiling for MONO on Windows.

The edits I made should have been enough, should we be updating the rest of ServUO to use __MonoCS__ instead? @Argalep What do you think?

**Comment by Argalep** [comment]
I searched a bit for the eye. it seems to be a better way to use _MonoCS_ instead of mono in the project.

**Comment by Elyrith** [comment]
Perhaps it's a bad idea after all, since it looks like __MonoCS__ isn't supported in Mono 5.0.0 anymore.
https://www.mono-project.com/docs/about-mono/releases/5.0.0/

In a moment I'll make an update that uses the check from the Mono documentation here:
https://www.mono-project.com/docs/faq/technical/#how-can-i-detect-if-am-running-in-mono

**Pull request closed without merging**
