### PR TITLE
Updates to Enemy of one formula

### PR DESCRIPTION
**Pull request by ppardalj**
This pull request:
- Updates Enemy of one spell damage bonus formula to OSI.
- Apply only new damage bonus calculation only if post-SA era, otherwise use classic bonus (always 50).
- Refactored spell implementation to remove dependency with PlayerMobile class. Now most spell mechanics are implemented in EnemyOfOne.cs

### CODE REVIEW

**Comment by kevin-10** [comment]
There is a small effect issue when you toggle EOO off.  Also, when it's first cast, the damage scalar isn't showing the proper damage increase.  I would assume this should show when you cast it, correct?

**Comment by ppardalj** [comment]
@kevin-10  what is the issue? For me looks similar to OSI, both "activate" and "deactivate" effects are played together.

Regarding damage scalar, it's updated when you first hit a target. OSI also behaves this way.

**Comment by kevin-10** [comment]
The pre-cast effects last too late night when the cast delay is set to TimeSpan.Zero for some reason.  In my testing on EA, when EOO is active, the delay is typically 1/2 of the normal cast time, not removed altogether. So, cutting the delay in half should fix the cosmetic issue.  Also, when a EOO target is determined, the cliloc on the buff icon changes to take into account what type of creature it is.  For example, a mongbat shows as mongbats so this is going to require some string hacking.

**Comment by kevin-10** [comment]
Late night = long

**Pull request merged**
