### PR TITLE
* add CounterfeitPlatinum

### PR DESCRIPTION
**Pull request by Argalep**
* add khaldun chest
* CultistsRitualTome hue fix.
* add PolishedMeteorite

### CODE REVIEW

**Comment by Argalep** [comment]
there are missing parts:

* Caddellite Crafting
* Caddellite Infused

i do not know them.

**Comment by kevin-10** [comment]
A couple things.

1. Why is the chest's ID flags set to none?  This may create some issues since it wont be flagged as a container anymore, especially since other containers use this ID.

2. You don't need a region to created that message. That message is generated in DetectHidden if the chest inherits IRevealableItem.

**Comment by Argalep** [comment]
Players must walk through the secret crates. how do we do it.

**Comment by Argalep** [comment]
@kevin-10 

If we put a hidden item in which the players can pass, if we put the chest in place when the secrecy of the item is removed, will it solve our problem?

**Comment by kevin-10** [comment]
I'm not sure. I'm looking at ItemData now, to see if we can override it for individual items, instead of item id's. We can run it as is, and address this next.

**Comment by kevin-10** [comment]
Are these items only passable when hidden in EA?

**Comment by Argalep** [comment]
Yes

> Are these items only passable when hidden in EA?

yes

**Comment by kevin-10** [comment]
So, if they are not hidden, they are not passable, like a decorative box?

**Comment by Argalep** [comment]
Yes

**Pull request merged**
