### PR TITLE
Fixs

### PR DESCRIPTION
**Pull request by Argalep**
* Exodus Ritual EA fix
* only pet kick Trammel Blackthorn Castle
* When the char disconnected from the storm level gump will appear in Blackthorn Castle (Trammel) and Ver Lor Reg
* Fezzik fix
* Add Nexus addon in Exodus Dungeon ([GenExodusNexus)
* Add Nexus Addon Game

### CODE REVIEW

**Comment by kevin-10** [comment]
Sorry dude, I'll will take a look when I get home.  Thanks for your patience!

**Comment by Argalep** [comment]
When do you check ?

**Comment by kevin-10** [comment]
Is there a command that generates this?

**Comment by kevin-10** [comment]
Disregard, found it.

**Pull request merged**
