### PR TITLE
Bug Fixs.

### PR DESCRIPTION
**Pull request by Argalep**
* Neville fix.
* BaseEscort Quest Gump Fix.
* Quester Escorts, the quest will be canceled when logout or killed.
* Remove Neville spawn
* Mannequin are used in private homes.

### CODE REVIEW

**Comment by kevin-10** [comment]
What was changed in PlayerMobile?

**Comment by Argalep** [comment]
```
private static void OnLogout(LogoutEventArgs e)
		{
            PlayerMobile pm = e.Mobile as PlayerMobile;

            #region Scroll of Alacrity
            if (pm.AcceleratedStart > DateTime.UtcNow)
			{
				pm.AcceleratedStart = DateTime.UtcNow;
				ScrollofAlacrity.AlacrityEnd(pm);
			}
			#endregion

            BaseFamiliar.OnLogout(pm);

            BaseEscort.DeleteEscort(pm);
        }
```


public override void OnDeath(Container c)
		
add

BaseEscort.DeleteEscort(this);

**Comment by kevin-10** [comment]
Roger that, thanks. Also, this compiles? I noticed it failed checks but that doesn't always tell the truth.

**Comment by Tasanar** [comment]
Seems to compile just fine

**Pull request merged**
